Repository ansible/ansible-lint-action, pull requests merged in 2022-03, with the labels that each got.

#69 Add self-test pipeline
  .github/workflows/self-test.yml
Labels: skip-changelog

#68 Start using creator-ee prebuilt image
  .github/workflows/self-test.yml
  Dockerfile
Labels: enhancement

#70 Enable release drafting pipeline
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
Labels: skip-changelog

#71 Enable pre-commit
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .yamllint
  action.yml
  tox.ini
Labels: skip-changelog

#72 Enable prettier
  .pre-commit-config.yaml
  README.md
  action.yml
Labels: skip-changelog

#73 Enable cspell
  .config/dictionary.txt
  .pre-commit-config.yaml
  cspell.config.yaml
  entrypoint.sh
Labels: skip-changelog

#74 Stop building the container
  Dockerfile
  README.md
  action.yml
Labels: major

#76 Remove obsolete entrypoint.sh
  entrypoint.sh
Labels: bug

#77 Change ansible-lint action icon
  action.yml
Labels: enhancement

#79 add docker:// to image name
  action.yml
Labels: bug

#82 Move tags on release
  .github/workflows/release.yml
Labels: skip-changelog

#89 Updated version of creator-ee to 0.4.0
  action.yml
Labels: bug

#91 Use ansible-lint 6.0.2
  action.yml
Labels: bug

#93 Fix moving tag on release
  .github/workflows/release.yml
Labels: bug, skip-changelog

#94 Update README.md with organization name
  README.md
Labels: bug

#97 Deprecate args and enable path as input
  README.md
  action.yml
Labels: bug
