Repository ansible/ansible-lint-action, pull requests merged in 2022-12, with the labels that each got.

#136 actions/checkout to v3 in README
  README.md
Labels: bug

#142 GHA cleanups
  .github/CODEOWNERS
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  tox.ini
Labels: skip-changelog

#143 Start using ghcr.io instead of quay.io
  action.yml
Labels: bug

#141 Update ansible-lint to 6.10.0
  action.yml
Labels: enhancement

#144 Remove verbosity args
  action.yml
Labels: bug

#145 Update example to include full checkout
  README.md
Labels: bug
